project_name: hyde-ipc

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
    main: ./cmd/main.go
    binary: "hyde-ipc-{{ .Version }}-{{ .Os }}-{{ .Arch }}"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}}

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      # - LICENSE # TODO: add license
      - README.md

nfpms:
  - vendor: "hyde-ipc"
    homepage: "https://github.com/HyDE-Project/hyde-ipc"
    maintainer: "HyDE-Project"
    description: "A lightweight event handler for Hyprland that executes custom scripts based on Hyprland IPC events."
    license: "MIT"
    bindir: /usr/bin

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"

release:
  github:
    owner: HyDE-Project
    name: hyde-ipc
  prerelease: auto
  draft: false
