[env]
BINARY_NAME = "hyde-itc"

# Target directory for binaries
BIN_DIR = "./bin"

# Source directory for debug binaries
TARGET_DEBUG_DIR = "./target/debug"

# Source directory for release binaries
TARGET_RELEASE_DIR = "./target/release"


[tasks.create-bin-dir]
description = "Ensures the ${BIN_DIR} directory exists."
category = "Setup"
script = ["mkdir -p ${BIN_DIR}"]

[tasks.build-debug]
description = "Builds the project in debug mode."
category = "Build"
command = "cargo"
args = ["build"]
dependencies = ["create-bin-dir"]

[tasks.copy-binary-debug]
description = "Copies the debug binary to ${BIN_DIR}."
category = "Build"
dependencies = ["build-debug"]
script = ["cp ${TARGET_DEBUG_DIR}/${BINARY_NAME} ${BIN_DIR}/${BINARY_NAME}"]

[tasks.build-and-copy-debug]
description = "Builds in debug mode and copies the binary."
category = "User"
dependencies = ["copy-binary-debug"]

[tasks.build-release]
description = "Builds the project in release mode."
category = "Build"
command = "cargo"
args = ["build", "--release"]
dependencies = ["create-bin-dir"]

[tasks.copy-binary-release]
description = "Copies the release binary to ${BIN_DIR}."
category = "Build"
dependencies = ["build-release"]
script = ["cp ${TARGET_RELEASE_DIR}/${BINARY_NAME} ${BIN_DIR}/${BINARY_NAME}"]

[tasks.build-and-copy-release]
description = "Builds in release mode and copies the binary."
category = "User"
dependencies = ["copy-binary-release"]


[tasks.default]
description = "Builds in debug mode and copies the binary (default action)."
alias = "build-and-copy-debug"


[tasks.release]
description = "Builds in release mode and copies the binary."
alias = "build-and-copy-release"

[tasks.build]
description = "Builds the project in debug mode (without copying)."
alias = "build-debug"
