[[reactions]]
event_type = { Window = "Opened" }
window_filter = "class:kitty"
dispatchers = [
  { name = "focus-window", args = ["class:kitty"] },
  { name = "toggle-floating" },
  { name = "resize-active", args = ["exact", "800", "600"] },
  { name = "center-window" },
]
